name: omia_tagger
channels:
  - conda-forge
  - defaults
# These dependencies worked to get Tensorflow working
#   on a GPU for training on my home desktop -
#   haven't successfully dockerized them yet
dependencies:
  - python=3.11
  - tensorflow-gpu>=2.13.1,<3.0
  - transformers>=4.35.0,<5.0
  - nltk>=3.8.1,<4.0
  - pytorch>=2.0.0,<3.0
