name: omia_tagger
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - tensorflow>=2.13.1,<3.0
  - transformers>=4.35.0,<5.0
  - nltk>=3.8.1,<4.0
  - pytorch>=2.0.0,<3.0
  - jupyterlab>=4.0,<5.0
